version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "LinchaiTheShinigami"  # Replace with your GitHub username
    assignees:
      - "LinchaiTheShinigami"  # Replace with your GitHub username